os: Visual Studio 2015
environment:
  matrix:
#  - TARGET: x86_64-pc-windows-msvc
#  - TARGET: i686-pc-windows-msvc
  - channel: stable
    target: x86_64-pc-windows-gnu
    MSYS_BITS: 64
  - channel: stable
    target: i686-pc-windows-gnu
    MSYS_BITS: 32
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
build: off
test_script:
  - cargo test --verbose
artifacts:
  - path: target\release\*.exe
