environment:
  matrix:
#  - TARGET: x86_64-pc-windows-msvc
#  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
    MSYS_BITS: 64
  - TARGET: i686-pc-windows-gnu
    MSYS_BITS: 32
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe" -FileName "rust-nightly.exe"
  - ps: .\rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - if defined MSYS_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS_BITS%\bin
  - rustc -vV
  - cargo -vV
  - gcc --version
build: false
build_script:
  - cargo build --release
test_script:
  - cargo test --verbose
artifacts:
  - path: target\release\*.exe
