[package]
name = "generic-dns-update"
version = "1.1.0"
authors = ["Damien Lecan <dev@dlecan.com>"]

[[bin]]
name="gdu"

[dependencies]
clap = "1"
log = "*"
env_logger = "*"
rust-xmlrpc = { git = "https://github.com/dlecan/rust-xmlrpc.git"}
rustc-serialize = "0.3"
regex = "0.1"
hyper = "0.7"
